# compose.yaml - Backend ONLY (Spring Boot + PostgreSQL on Port 5433)

services:
  # Service name ('app') is default, but using container_name for clarity
  app:
    # This name MUST match what the frontend's NEXT_PUBLIC_API_URL expects
    container_name: springboot-app-dev
    build:
      # Adjust context if this file isn't in the backend project root
      context: . # Assumes this file is in the Spring Boot project root
      dockerfile: Dockerfile.dev
    environment:
      # Email environment
      FRONT_END_URL: http://localhost:3000
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_USERNAME: testingpilot6@gmail.com
      SPRING_MAIL_PASSWORD: aybveadnbpjnwlmd # Consider secrets/.env file

      # --- Database Environment (Connecting to postgres-db on internal port 5433) ---
      SPRING_DATASOURCE_URL: jdbc:postgresql://96.9.81.189:6436/postgres # <-- Port updated to 5433
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Relative3
      SPRING_MAIL_SUPPORT_EMAIL: yumateb@gmail.com
      GOOGLE_CLIENT_ID: 140196654685-tnjva118amqpnth7q1spj9fjtt2ugfd7.apps.googleusercontent.com
      GITHUB_API: https://github.com
      GITHUB_USER_API: https://api.github.com/user
      GITHUB_CLIENT_ID: Ov23li6h1WXlLjfhqrLS
      GITHUB_CLIENT_SECRET: eaebb7ac2a67da2a67015bfc002db025fac513b2
      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: testpilot
      MINIO_SECRET_KEY: q4MJqG0DnBLsx
      MINIO_BUCKET_NAME: testpilot

      # Optional: Add profile if needed
      # SPRING_PROFILES_ACTIVE: dev
    volumes:
      # Mount source code for potential live reload (depends on mvn setup)
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
      # Use a named volume for Maven dependencies cache
      - maven_repo:/root/.m2
    ports:
      # Map host port 8080 to container port 8080
      - "8080:8080"
    command: mvn spring-boot:run
# Define named volumes used by this service
volumes:
  maven_repo:
  postgres_data: # Define the volume for PostgreSQL persistence
  storage:


# Define the external network
#networks:
networks:
  testing-pilot-network:
    driver: bridge
#    external: true # <-- Mark it as externally created