services:
  app:
    container_name: springboot-app-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      FRONT_END_URL: http://localhost:3000
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_USERNAME: testingpilot6@gmail.com
      SPRING_MAIL_PASSWORD: aybveadnbpjnwlmd
      SPRING_DATASOURCE_URL: jdbc:postgresql://96.9.81.189:6436/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Relative3
      SPRING_MAIL_SUPPORT_EMAIL: yumateb@gmail.com
      GOOGLE_CLIENT_ID: 140196654685-tnjva118amqpnth7q1spj9fjtt2ugfd7.apps.googleusercontent.com
      GITHUB_API: https://github.com
      GITHUB_USER_API: https://api.github.com/user
      GITHUB_CLIENT_ID: Ov23li6h1WXlLjfhqrLS
      GITHUB_CLIENT_SECRET: eaebb7ac2a67da2a67015bfc002db025fac513b2
      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: testpilot
      MINIO_SECRET_KEY: q4MJqG0DnBLsx
      MINIO_BUCKET_NAME: testpilot
      SECURITY_USERNAME: testpilotdev
      SECURITY_PASSWORD: f8f936b937f74e2f9b2f13a02065d5d6
      # Fixed RabbitMQ connection settings
      RABBITMQ_HOST: rabbitmq-testpilot
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: testpilot
      RABBITMQ_PASSWORD: Testpilot123@
    volumes:
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
      - maven_repo:/root/.m2
    ports:
      - "8080:8080"
    networks:
      - testing-pilot-network
    depends_on:
      rabbitmq:
        condition: service_healthy

    command: mvn spring-boot:run

  rabbitmq:
    container_name: rabbitmq-testpilot
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: testpilot
      RABBITMQ_DEFAULT_PASS: Testpilot123@
    networks:
      - testing-pilot-network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

volumes:
  maven_repo:
  postgres_data:
  storage:

networks:
  testing-pilot-network:
    driver: bridge