spring.servlet.multipart.file-size-threshold=2B
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=30MB

minio.url=http://localhost:9000
minio.access.key=testpilot
minio.access.secret=q4MJqG0'D}]nBLsx#J5
minio.bucket.name=testpilot
 

spring.jackson.deserialization.fail-on-unknown-properties=true

###################################### ? Database Configuration ##########################
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://96.9.81.189:6436/postgres
spring.datasource.username=postgres
spring.datasource.password=Relative3

###################################### ? Environment ####################################
app.dev.frontend.url=http://localhost:3000

###################################### ? Spring Security Default User ####################
spring.security.user.name=user
spring.security.user.password=Test12345_

###################################### ? DevTools (Hot Reload) ##########################
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

###################################### ? Email Configuration ###########################
spring.mail.host=smtp.gmail.com
spring.mail.username=testingpilot6@gmail.com
spring.mail.password=aybveadnbpjnwlmd
spring.mail.support_email=yumateb@gmail.com

# Additional mail properties
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.smtp.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=${SPRING_MAIL_HOST}

###################################### ? Spring Actuator Health Check ###################
management.endpoints.web.exposure.include=health,info,metrics

###################################### ? OTP Configuration #############################
otp.expiration=5  # in minutes

###################################### ? Google OAuth ##################################
google.client-id=140196654685-tnjva118amqpnth7q1spj9fjtt2ugfd7.apps.googleusercontent.com

###################################### ? GitHub OAuth ##################################
github.api=https://api.github.com
github.client-id=Ov23lifJjaWmfYe67xnt
github.client-secret=b5146e03673a7a6b4ba15ea7df8c0a7b388828e6
github.user-api=https://api.github.com/user