package com.both.testing_pilot_backend.model.enums;

public enum TriggerType {
    SINGLE_TEST_CASE, REQUEST_TEST_CASES, FOLDER_TEST_CASES, COLLECTION_TEST_CASES, PROJECT_TEST_CASES, SELECTED_TEST_CASES, SINGLE_REQUEST, SELECTED_REQUESTS
}
